CREATE TABLE IF NOT EXISTS services (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, duration_minutes INTEGER NOT NULL, price_aud DOUBLE PRECISION NOT NULL, description TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS bookings (
  id TEXT PRIMARY KEY, service_id INTEGER NOT NULL REFERENCES services(id), location TEXT NOT NULL,
  start TEXT NOT NULL, end TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, note TEXT,
  payment_status TEXT NOT NULL DEFAULT 'pending_verification', payment_method TEXT, payer_phone TEXT, transaction_id TEXT, created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_active_slot ON bookings(start) WHERE payment_status IN ('pending_verification','pending','paid');
