import json, os, uuid
from db import db as connect_db, IS_POSTGRES, DB_INTEGRITY_ERROR
from datetime import datetime, timedelta, date
from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
from pathlib import Path
ROOT=Path(__file__).parent; DB=ROOT/'appointments.db'
SERVICES=[('Electrical systems review',60,180.0,'Power distribution, protection, load flow, and energy monitoring.'),('Automation + control consult',60,180.0,'Instrumentation, IoT, SCADA, and operational visibility.'),('Data science discovery',60,160.0,'Forecasting, anomaly detection, and predictive maintenance.'),('Analytics product session',90,240.0,'Data pipelines, dashboards, and production planning.')]
def db():
 return connect_db()
def init():
 c=db()
 c.execute('CREATE TABLE IF NOT EXISTS services(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT,duration_minutes INTEGER,price_aud DOUBLE PRECISION,description TEXT)' if IS_POSTGRES else 'CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY,name TEXT,duration_minutes INTEGER,price_aud REAL,description TEXT)')
 c.execute('CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,service_id INTEGER NOT NULL,location TEXT NOT NULL,start TEXT NOT NULL,end TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,note TEXT,payment_status TEXT NOT NULL DEFAULT "pending_verification",payment_method TEXT,payer_phone TEXT,transaction_id TEXT,created_at TEXT NOT NULL)')
 c.execute('CREATE UNIQUE INDEX IF NOT EXISTS unique_active_slot ON bookings(start) WHERE payment_status IN ("pending_verification","pending","paid")')
 cols={r['column_name'] if IS_POSTGRES else r['name'] for r in c.execute("SELECT column_name FROM information_schema.columns WHERE table_name='bookings'" if IS_POSTGRES else 'PRAGMA table_info(bookings)')}
 for name in ('payment_method','payer_phone','transaction_id'):
  if name not in cols:c.execute(f'ALTER TABLE bookings ADD COLUMN {name} TEXT')
 if c.execute('SELECT COUNT(*) AS n FROM services').fetchone()['n']==0:c.executemany('INSERT INTO services(name,duration_minutes,price_aud,description) VALUES(?,?,?,?)',SERVICES)
 c.commit();c.close()
def json_body(h):
 n=int(h.headers.get('Content-Length','0'));return json.loads(h.rfile.read(n) or b'{}')
def slots(service_id,day):
 c=db();s=c.execute('SELECT * FROM services WHERE id=?',(service_id,)).fetchone();taken=[(datetime.fromisoformat(r['start']),datetime.fromisoformat(r['end'])) for r in c.execute('SELECT start,end FROM bookings WHERE start LIKE ? AND payment_status IN ("pending_verification","pending","paid")',(day+'%',))];c.close();out=[];d=datetime.fromisoformat(day+'T09:00');end=datetime.fromisoformat(day+'T17:00');
 while d+timedelta(minutes=s['duration_minutes'])<=end:
  iso=d.isoformat(timespec='minutes');
  if d.weekday()<5 and not any(d<busy_end and d+timedelta(minutes=s['duration_minutes'])>busy_start for busy_start,busy_end in taken):out.append({'start':iso,'label':d.strftime('%I:%M %p').lstrip('0')})
  d+=timedelta(minutes=30)
 return out
def confirmation_url(bid, service, email):
 return f"/booking-confirmation.html?id={bid}&payment=pending_verification"

def ics(row):
 return f'BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Your Name//Appointments//EN\nBEGIN:VEVENT\nUID:{row["id"]}@yourname.engineer\nDTSTAMP:{datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")}\nDTSTART:{row["start"].replace("-","").replace(":","")}00\nDTEND:{row["end"].replace("-","").replace(":","")}00\nSUMMARY:{row["service_name"]}\nDESCRIPTION:Technical session with Your Name\nEND:VEVENT\nEND:VCALENDAR\n'
class App(SimpleHTTPRequestHandler):
 def end(self,code=200,typ='application/json'):self.send_response(code);self.send_header('Content-Type',typ);self.send_header('Access-Control-Allow-Origin','*');self.end_headers()
 def write(self,obj):self.wfile.write(json.dumps(obj).encode())
 def do_OPTIONS(self):self.end(204)
 def do_GET(self):
  u=urlparse(self.path);q=parse_qs(u.query)
  if u.path=='/api/admin/bookings':
   if not os.getenv('ADMIN_TOKEN') or q.get('token',[''])[0]!=os.getenv('ADMIN_TOKEN'): self.end(401);self.write({'error':'Unauthorized'});return
   c=db();rows=c.execute('SELECT b.*,s.name service_name FROM bookings b JOIN services s ON s.id=b.service_id ORDER BY b.start DESC').fetchall();c.close();self.end();self.write([dict(r) for r in rows]);return
  if u.path.startswith('/api/bookings/') and u.path.count('/')==3:
   bid=u.path.split('/')[3];c=db();r=c.execute('SELECT b.*,s.name service_name,s.duration_minutes FROM bookings b JOIN services s ON s.id=b.service_id WHERE b.id=?',(bid,)).fetchone();c.close()
   if not r:self.end(404);self.write({'error':'Booking not found'});return
   self.end();self.write({'id':r['id'],'service':r['service_name'],'location':r['location'],'start':r['start'],'end':r['end'],'status':r['payment_status'],'payment_method':r['payment_method']});return
  if u.path=='/api/health':
   self.end();self.write({'ok':True,'database':'postgres' if IS_POSTGRES else 'sqlite','time':datetime.utcnow().isoformat()+'Z'});return
  if u.path=='/api/services':
   c=db();self.end();self.write([dict(x) for x in c.execute('SELECT * FROM services')]);c.close();return
  if u.path=='/api/availability':
   try:self.end();self.write({'date':q['date'][0],'slots':slots(int(q['service_id'][0]),q['date'][0])})
   except Exception as e:self.end(400);self.write({'error':str(e)})
   return
  if u.path.startswith('/api/bookings/') and u.path.endswith('/calendar.ics'):
   bid=u.path.split('/')[3];c=db();r=c.execute('SELECT b.*,s.name service_name FROM bookings b JOIN services s ON s.id=b.service_id WHERE b.id=?',(bid,)).fetchone();c.close();
   if not r:self.end(404);self.write({'error':'Booking not found'});return
   self.end(200,'text/calendar');self.wfile.write(ics(r).encode());return
  return super().do_GET()
 def do_POST(self):
  if self.path.startswith('/api/bookings/') and self.path.endswith('/cancel'):
   bid=self.path.split('/')[3];body=json_body(self);c=db();r=c.execute('SELECT * FROM bookings WHERE id=? AND lower(email)=lower(?)',(bid,body.get('email',''))).fetchone()
   if not r:self.end(404);self.write({'error':'Booking not found or email did not match'});return
   c.execute('UPDATE bookings SET payment_status="cancelled" WHERE id=?',(bid,));c.commit();c.close();self.end();self.write({'ok':True,'status':'cancelled'});return
  if self.path.startswith('/api/bookings/') and self.path.endswith('/reschedule'):
   bid=self.path.split('/')[3];body=json_body(self);c=db();r=c.execute('SELECT b.*,s.duration_minutes FROM bookings b JOIN services s ON s.id=b.service_id WHERE b.id=? AND lower(b.email)=lower(?)',(bid,body.get('email',''))).fetchone()
   if not r:self.end(404);self.write({'error':'Booking not found or email did not match'});return
   if r['payment_status']=='cancelled':self.end(409);self.write({'error':'Cancelled bookings cannot be rescheduled'});return
   start=datetime.fromisoformat(body['start']);end=start+timedelta(minutes=r['duration_minutes'])
   if start<datetime.now():self.end(400);self.write({'error':'Choose a future time'});return
   conflict=c.execute('SELECT 1 FROM bookings WHERE id!=? AND payment_status IN ("pending_verification","pending","paid") AND start < ? AND end > ? LIMIT 1',(bid,end.isoformat(timespec='minutes'),start.isoformat(timespec='minutes'))).fetchone()
   if conflict:self.end(409);self.write({'error':'That time overlaps another booking'});return
   c.execute('UPDATE bookings SET start=?,end=? WHERE id=?',(start.isoformat(timespec='minutes'),end.isoformat(timespec='minutes'),bid));c.commit();c.close();self.end();self.write({'ok':True,'start':start.isoformat(timespec='minutes'),'end':end.isoformat(timespec='minutes')});return
  if self.path.startswith('/api/admin/bookings/'):
   q=parse_qs(urlparse(self.path).query)
   if not os.getenv('ADMIN_TOKEN') or q.get('token',[''])[0]!=os.getenv('ADMIN_TOKEN'): self.end(401);self.write({'error':'Unauthorized'});return
   bid=self.path.split('/')[4].split('?')[0];body=json_body(self);status=body.get('status')
   if status not in ('pending_verification','paid','cancelled'): self.end(400);self.write({'error':'Invalid status'});return
   c=db();c.execute('UPDATE bookings SET payment_status=? WHERE id=?',(status,bid));c.commit();c.close();self.end();self.write({'ok':True,'booking_id':bid,'status':status});return
  if self.path!='/api/bookings':self.end(404);self.write({'error':'Not found'});return
  try:
   b=json_body(self);c=db();s=c.execute('SELECT * FROM services WHERE id=?',(b['service_id'],)).fetchone();start=datetime.fromisoformat(b['start']);end=start+timedelta(minutes=s['duration_minutes']);
   if start<datetime.now():raise ValueError('Choose a future time')
   conflict=c.execute('SELECT 1 FROM bookings WHERE payment_status IN ("pending_verification","pending","paid") AND start < ? AND end > ? LIMIT 1',(end.isoformat(timespec='minutes'),start.isoformat(timespec='minutes'))).fetchone()
   if conflict: raise sqlite3.IntegrityError('overlapping slot')
   bid=uuid.uuid4().hex;method=b.get('payment_method','').lower();phone=b.get('payer_phone','').strip();tx=b.get('transaction_id','').strip();
   if method not in ('bkash','rocket'): raise ValueError('Choose bKash or Rocket')
   if not phone or not tx: raise ValueError('Payer phone and transaction ID are required')
   c.execute('INSERT INTO bookings(id,service_id,location,start,end,name,email,note,payment_method,payer_phone,transaction_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',(bid,s['id'],b['location'],start.isoformat(timespec='minutes'),end.isoformat(timespec='minutes'),b['name'],b['email'],b.get('note',''),method,phone,tx,datetime.utcnow().isoformat()))
   c.commit();c.close();self.end(201);self.write({'booking_id':bid,'status':'pending_verification','payment_method':method,'confirmation_url':confirmation_url(bid,s,b['email'])})
  except DB_INTEGRITY_ERROR:self.end(409);self.write({'error':'That time was just booked. Please choose another available slot.'})
  except Exception as e:self.end(400);self.write({'error':str(e)})
if __name__=='__main__':init();ThreadingHTTPServer(('0.0.0.0',8000),lambda *a,**k:App(*a,directory=str(ROOT),**k)).serve_forever()
